# Tratamento de Exce√ß√µes

[üìΩ Veja esta v√≠deo-aula no Youtube](https://youtu.be/HtVJc_7FzYs)

---
> Let's face it, bad things happen. Networks partition, servers crash, remote endpoints become non-responsive. And when bad things happen, exceptions get thrown. And when exceptions get thrown, people die. Okay, maybe that's a bit dramatic, but the point is, exceptions are a fact of software development.

[Chris Patterson, MassTransit docs](https://masstransit.io/documentation/concepts/exceptions)

---
O .NET Core trata situa√ß√µes inesperadas dentro de um programa atrav√©s do seu mecanismo de exce√ß√µes. Segundo a [documenta√ß√£o](https://docs.microsoft.com/pt-br/dotnet/standard/exceptions/), uma exce√ß√£o √© "_qualquer condi√ß√£o de erro ou comportamento inesperado encontrado por um programa em execu√ß√£o_", ou seja, erros que n√£o podem ser pegos pelo compilador j√° que s√≥ ocorrem com o programa em execu√ß√£o.

O correto uso das ferramentas para tratamento de exce√ß√µes do C# √© essencial para a cria√ß√£o de programas confi√°veis e com uma experi√™ncia do usu√°rio adequada.

## Capturando uma exce√ß√£o

Quando um erro ocorre, o C# ter√° que finalizar o programa, a menos que haja algum tratamento por parte do programa. Fazemos esse tratamento envolvendo o c√≥digo que poder√° gerar o erro em um bloco `try...catch`:

```cs
try
{
    // comando(s) que podem gerar comportamentos inesperados
}
catch
{
    // c√≥digo que ser√° executado em caso de ocorr√™ncia de alguma exce√ß√£o
}
```

O bloco `try` deve conter os comandos que cont√©m erros em potencial. Ele ser√° executado integralmente caso nenhuma exce√ß√£o seja disparada, e depois seguir√° para o primeiro comando ap√≥s o bloco `catch`.

O bloco `catch` s√≥ ser√° executado caso alguma exce√ß√£o ocorra.

## Obtendo informa√ß√µes sobre a exce√ß√£o

Voc√™ pode saber mais sobre o erro ocorrido atrav√©s da seguinte sintaxe:

```cs
try
{
    // ...
}
catch (Exception e)
{
    // ...
}
```

Dessa maneira, `e` (ou qualquer outro nome que voc√™ quiser) √© uma vari√°vel que cont√©m todas as informa√ß√µes sobre o erro. As mais importantes:

* `Message` cont√©m a mensagem;
* `GetType()` retorna o tipo da exce√ß√£o.

Ex.:

```cs
// ...
catch(Exception ex)
{
    Console.WriteLine($"Erro encontrado: {ex.Message}");
    Console.WriteLine($"Tipo da exce√ß√£o: {ex.GetType()}");
}
```

## Relan√ßando a exce√ß√£o

Caso seja inclu√≠do um bloco `catch`, a exce√ß√£o poder√° n√£o mais ser√° processada pelo .NET. Nessas situa√ß√µes o programa continuar√° normalmente, a menos que o programador especifique que a exce√ß√£o deve ser relan√ßada.

Para relan√ßar uma exce√ß√£o:

```cs
// ...
catch (Exception ex)
{
    // comandos de tratamento de erro...
    throw ex;
}
```

## Lan√ßando uma exce√ß√£o personalizada

Voc√™ pode lan√ßar uma exce√ß√£o personalizada em qualquer parte do seu c√≥digo, de acordo com sua necessidade. Escolha o tipo adequado, instancie um objeto de exce√ß√£o do tipo adequado e use `throw`.

Ex.:
```cs
throw new ArgumentException("O valor informado n√£o √© v√°lido.");
```

Mais detalhes sobre boas pr√°ticas no lan√ßamento de exce√ß√µes na [documenta√ß√£o](https://docs.microsoft.com/pt-br/dotnet/standard/design-guidelines/using-standard-exception-types).

## Tipos de exce√ß√£o

O .NET utiliza uma √°rvore de tipos de exce√ß√£o. Segue uma lista resumida:

- `Exception`: todas as exce√ß√µes
  - `IndexOutOfRangeException`: quando um arranjo √© acessado com um √≠ndice inexistente
  - `NullReferenceException`: quando um objeto √© acessado e cont√©m o valor `null`
  - `InvalidOperationException`: quando uma opera√ß√£o √© executada em um estado inv√°lido
  - `DivideByZeroException`: quando acontece uma divis√£o por zero
  - `OverflowException`: quando um n√∫mero est√° al√©m do limite do tipo de dado esperado
  - `FormatException`: quando um dado est√° em formato inv√°lido
  - `ArgumentException`: todas as exce√ß√µes referentes a argumentos inv√°lidos
    - `ArgumentNullException`: quando um argumento √© passado incorretamente com o valor `null`
    - `ArgumentOutOfRangeException`: quando um argumento est√° fora dos limites esperados

Uma lista detalhada pode ser encontrada na [documenta√ß√£o](https://docs.microsoft.com/pt-br/dotnet/standard/exceptions/#common-exceptions).

## M√∫ltiplos `catch`'s

Voc√™ pode utilizar m√∫ltiplos blocos `catch` para tratar diferentes tipos de erros. Use os tipos mais espec√≠ficos primeiro, j√° que ao entrar em um bloco, os demais n√£o ser√£o executados. Veja um exemplo abaixo, no programa da v√≠deo-aula.

Programa da [v√≠deo-aula](https://youtu.be/HtVJc_7FzYs):

```cs
using System;

namespace AulaExcecoes
{
    class Program
    {
        static void Main(string[] args)
        {
            decimal x, y, r;

            try
            {
                // comandos pass√≠veis de exce√ß√£o
                Console.Write("x = ");
                x = Convert.ToDecimal(Console.ReadLine());

                Console.Write("y = ");
                y = Convert.ToDecimal(Console.ReadLine());

                if (x < 0 || y < 0)
                {
                    throw new ArgumentException("N√£o s√£o aceitos n√∫meros negativos.");
                }

                r = x / y;

                Console.WriteLine($"r = {r:N}");
            }
            catch(DivideByZeroException)
            {
                Console.WriteLine("N√£o √© poss√≠vel dividir por zero.");
            }
            catch(ArgumentException)
            {
                Console.WriteLine("N√£o s√£o aceitos n√∫meros negativos.");
            }            
            catch(OverflowException)
            {
                Console.WriteLine("N√∫mero inv√°lido.");
            }
            catch(FormatException)
            {
                Console.WriteLine("N√∫mero em formato inv√°lido.");
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Erro gen√©rico: {ex.Message}");
                Console.WriteLine($"Tipo: {ex.GetType()}");
                throw ex;
            }
            Console.WriteLine("Final do programa.");
        }
    }
}
```
